# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awiki < Formula
  desc "Explore and maintain flat-file Markdown wikis"
  homepage "https://github.com/corca-ai/awiki"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.0/awiki_0.1.0_darwin_amd64.tar.gz"
      sha256 "a5d39cdfe64631d3a809be92d8e8256d6b3e45b37472a41093179b947fa0db1d"

      define_method(:install) do
        bin.install "awiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.0/awiki_0.1.0_darwin_arm64.tar.gz"
      sha256 "7967b00cee4b8e4f99e006e0226eeb7483501f5f48ce2ca2c13929cdf4bb59f8"

      define_method(:install) do
        bin.install "awiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.0/awiki_0.1.0_linux_amd64.tar.gz"
      sha256 "62fe9a698dd8991d75940e6321a40c328255bcceaf413aac1bc46ac54d3c1dcb"
      define_method(:install) do
        bin.install "awiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.0/awiki_0.1.0_linux_arm64.tar.gz"
      sha256 "0d0ac421d1f5091306349521852affa30d4e3bf0a9e5859e252b5d54c66d19f8"
      define_method(:install) do
        bin.install "awiki"
      end
    end
  end

  test do
    system bin/"awiki", "version"
  end
end
