# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrakenSpacesCli < Formula
  desc "CLI for Craken Spaces"
  homepage "https://github.com/corca-ai/craken-spaces-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/craken-spaces-cli/releases/download/v0.2.0/craken_0.2.0_darwin_amd64.tar.gz"
      sha256 "caa61ff646ed466e05b053dd290d75b9c3abb37bd4f1dd87f6a12004156910d7"

      define_method(:install) do
        bin.install "spaces"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/craken-spaces-cli/releases/download/v0.2.0/craken_0.2.0_darwin_arm64.tar.gz"
      sha256 "a9d3a433792366bc3f3ca298f4155257e103d0648e08e4100803237c57193717"

      define_method(:install) do
        bin.install "spaces"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-spaces-cli/releases/download/v0.2.0/craken_0.2.0_linux_amd64.tar.gz"
      sha256 "3594a64190fe601d16fd22204da9d249d11c51edbbc872d67680f85a52a62cd0"
      define_method(:install) do
        bin.install "spaces"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-spaces-cli/releases/download/v0.2.0/craken_0.2.0_linux_arm64.tar.gz"
      sha256 "e31371f02c7f47cb2ec93c801d467a75b389bdd596d615d1e28fab7fdc8550dd"
      define_method(:install) do
        bin.install "spaces"
      end
    end
  end

  test do
    system bin/"spaces", "version"
  end
end
