# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craken < Formula
  desc "CLI for Craken managed workspaces"
  homepage "https://github.com/corca-ai/craken-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.0/craken_0.1.0_darwin_amd64.tar.gz"
      sha256 "7e0d8c7327e838701aec6b0f7eb0a407ce5ad325ed8a5acfd6597fecd632096c"

      define_method(:install) do
        bin.install "craken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.0/craken_0.1.0_darwin_arm64.tar.gz"
      sha256 "1cc317bc449a0ebefe09c44d1441c104ebe5e4408f89973546dbddc8d0fa7be0"

      define_method(:install) do
        bin.install "craken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.0/craken_0.1.0_linux_amd64.tar.gz"
      sha256 "6db6bf5006f9f172dc4e7930d2f7f45338c626641e23a72657563ee24517e428"
      define_method(:install) do
        bin.install "craken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.0/craken_0.1.0_linux_arm64.tar.gz"
      sha256 "c1392ca3833cfbc7f4e5e5a998075df4e0fda3efa27e18dbdbdefd60dc443d60"
      define_method(:install) do
        bin.install "craken"
      end
    end
  end

  test do
    system bin/"craken", "version"
  end
end
