# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craken < Formula
  desc "CLI for Craken managed workspaces"
  homepage "https://github.com/corca-ai/craken-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.0/craken_0.1.0_darwin_amd64.tar.gz"
      sha256 "6c0c7112b090bba102bab263e200ea1985eca6d6bd18bf5d6e25985c06761ebe"

      define_method(:install) do
        bin.install "craken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.0/craken_0.1.0_darwin_arm64.tar.gz"
      sha256 "f563d9b5e3adeec1615ea8d851d8457b3f6be40e509e680368841d077e485e59"

      define_method(:install) do
        bin.install "craken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.0/craken_0.1.0_linux_amd64.tar.gz"
      sha256 "0d3b00300ed440128a55f90325a965b93e59bddbc35f51f82bf471fdab28ebdf"
      define_method(:install) do
        bin.install "craken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.0/craken_0.1.0_linux_arm64.tar.gz"
      sha256 "e38fc3254d272802c6a7883f6b31f44d1be1683f26ed0c5271c28feabd9f4f71"
      define_method(:install) do
        bin.install "craken"
      end
    end
  end

  test do
    system bin/"craken", "version"
  end
end
