# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrakenSpacesCli < Formula
  desc "CLI for Craken Spaces"
  homepage "https://github.com/corca-ai/craken-spaces-cli"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/craken-spaces-cli/releases/download/v0.8.0/craken_0.8.0_darwin_amd64.tar.gz"
      sha256 "a8cd670fcd66540f2f5d56c306c87dc89f6213bfb69cc382875afed5a0be512f"

      define_method(:install) do
        bin.install "spaces"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/craken-spaces-cli/releases/download/v0.8.0/craken_0.8.0_darwin_arm64.tar.gz"
      sha256 "d2324ea00df7f9d7ba2f41b4cfb9de913d26afd7586f18628763f9aab99954bb"

      define_method(:install) do
        bin.install "spaces"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-spaces-cli/releases/download/v0.8.0/craken_0.8.0_linux_amd64.tar.gz"
      sha256 "1c1353382fb3c69bc18af5c5eb61da9b536ccb530b85250e05cef4ea25bec6d9"
      define_method(:install) do
        bin.install "spaces"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-spaces-cli/releases/download/v0.8.0/craken_0.8.0_linux_arm64.tar.gz"
      sha256 "839161c99719c40a7d19c636dc8b2070a544d7066693ce1a10bf2a0a1adef278"
      define_method(:install) do
        bin.install "spaces"
      end
    end
  end

  test do
    system bin/"spaces", "version"
  end
end
