# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SahCli < Formula
  desc "SCIENCE@home worker CLI for background agent contributions"
  homepage "https://github.com/corca-ai/sah-cli"
  version "0.2.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/corca-ai/sah-cli/releases/download/v0.2.2/sah_0.2.2_darwin_amd64.tar.gz"
    sha256 "9347d6621a257e2461129b5f50b6b47e918fe6f75e67934ede05eb6cf12768e1"

    define_method(:install) do
      bin.install "sah"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/corca-ai/sah-cli/releases/download/v0.2.2/sah_0.2.2_darwin_arm64.tar.gz"
    sha256 "2795a6c4ad5811f7fa7e8d114d26f87f8e6d076bdd30d95d8d462f152545e27f"

    define_method(:install) do
      bin.install "sah"
    end
  end

  test do
    system bin/"sah", "version"
  end
end
