# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SahCli < Formula
  desc "SCIENCE@home worker CLI for background agent contributions"
  homepage "https://github.com/corca-ai/sah-cli"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/sah-cli/releases/download/v0.6.2/sah_0.6.2_darwin_amd64.tar.gz"
      sha256 "0c59f1fa29e415ae8b818b62ac7a6205b0dd3bf9f46dff47af78e62d8c742467"

      define_method(:install) do
        bin.install "sah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/sah-cli/releases/download/v0.6.2/sah_0.6.2_darwin_arm64.tar.gz"
      sha256 "7437110307cfd7d46fff0d272cb1b0d27afdde0ae82f32afcde57e6a8dddebd9"

      define_method(:install) do
        bin.install "sah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/sah-cli/releases/download/v0.6.2/sah_0.6.2_linux_amd64.tar.gz"
      sha256 "eafcc99ce09294215e910a63d8064e41036bec9bf899324734b1bdcbcf3f5cfc"
      define_method(:install) do
        bin.install "sah"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/sah-cli/releases/download/v0.6.2/sah_0.6.2_linux_arm64.tar.gz"
      sha256 "2542ce4efedfd1e7b263f28d4d455e1bd361de35d6ef3720b4fb8d410f99bbce"
      define_method(:install) do
        bin.install "sah"
      end
    end
  end

  test do
    system bin/"sah", "version"
  end
end
