# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specdown < Formula
  desc "Executable specifications in Markdown"
  homepage "https://github.com/corca-ai/specdown"
  version "0.23.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/specdown/releases/download/v0.23.0/specdown_0.23.0_darwin_amd64.tar.gz"
      sha256 "de23461cd1fbb181637226f3371115573012f3320b0a958c3c70f49ba4424429"

      define_method(:install) do
        bin.install "specdown"
        bin.install "specdown-adapter-shell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/specdown/releases/download/v0.23.0/specdown_0.23.0_darwin_arm64.tar.gz"
      sha256 "594fbe69a3b478587079bc76cac1a7b16f11d3eab81fb53fbc441e2e96046dcd"

      define_method(:install) do
        bin.install "specdown"
        bin.install "specdown-adapter-shell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/specdown/releases/download/v0.23.0/specdown_0.23.0_linux_amd64.tar.gz"
      sha256 "ee1ba45e34fddb49fb8c174d48afccf66016e435deec67735449a8de50a390b5"
      define_method(:install) do
        bin.install "specdown"
        bin.install "specdown-adapter-shell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/specdown/releases/download/v0.23.0/specdown_0.23.0_linux_arm64.tar.gz"
      sha256 "736b20f62393a59b1b473dbd7606b5be857677355b05b5beace10286b0b3be22"
      define_method(:install) do
        bin.install "specdown"
        bin.install "specdown-adapter-shell"
      end
    end
  end

  test do
    system bin/"specdown", "version"
  end
end
