# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awiki < Formula
  desc "Explore and maintain flat-file Markdown wikis"
  homepage "https://github.com/corca-ai/awiki"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.2/awiki_0.1.2_darwin_amd64.tar.gz"
      sha256 "813836a14bd0b538b6115c4d873adaa83e342066015c4c8d761dc72feade8886"

      define_method(:install) do
        bin.install "awiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.2/awiki_0.1.2_darwin_arm64.tar.gz"
      sha256 "c62b87f695ca3336d68113c04bebb62706f22b99516cbdb9fa3e0ff435b1b9a7"

      define_method(:install) do
        bin.install "awiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.2/awiki_0.1.2_linux_amd64.tar.gz"
      sha256 "0a0c2fbf23f7a7c973a207d1674ab6ca7f8dc490690f5f2875bc74414c217f7a"
      define_method(:install) do
        bin.install "awiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.2/awiki_0.1.2_linux_arm64.tar.gz"
      sha256 "3f69a229b844f95e5a2944fb7ce62f3a537acbba195b71f17fba72533d29937b"
      define_method(:install) do
        bin.install "awiki"
      end
    end
  end

  test do
    system bin/"awiki", "version"
  end
end
