# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awiki < Formula
  desc "Explore and maintain flat-file Markdown wikis"
  homepage "https://github.com/corca-ai/awiki"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.1/awiki_0.1.1_darwin_amd64.tar.gz"
      sha256 "4f1fb889170595d0776d89261c7c9a453ca195224840ee923d2b378eab471fd7"

      define_method(:install) do
        bin.install "awiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.1/awiki_0.1.1_darwin_arm64.tar.gz"
      sha256 "e468bddf3add8f644be76adf1efc0e4f620a59ce9da78f8475f064f23aed5087"

      define_method(:install) do
        bin.install "awiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.1/awiki_0.1.1_linux_amd64.tar.gz"
      sha256 "5ad8eeaf1855f570e6d828ff9da3ba225116011ae401d213fe39c2669bf90f26"
      define_method(:install) do
        bin.install "awiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.1/awiki_0.1.1_linux_arm64.tar.gz"
      sha256 "357a10b03ec9504552ad8442b6bd6e4e331c4678ce66f633baf4fd800f4e9204"
      define_method(:install) do
        bin.install "awiki"
      end
    end
  end

  test do
    system bin/"awiki", "version"
  end
end
