# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awiki < Formula
  desc "Explore and maintain flat-file Markdown wikis"
  homepage "https://github.com/corca-ai/awiki"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.4/awiki_0.1.4_darwin_amd64.tar.gz"
      sha256 "4bef5bc0d1940c77252b10415123f8a488b051e52127da2d32e6ade460d68008"

      define_method(:install) do
        bin.install "awiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.4/awiki_0.1.4_darwin_arm64.tar.gz"
      sha256 "d90b561afda921e5061985822383e7d6160e30abe246332135192efafc743420"

      define_method(:install) do
        bin.install "awiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.4/awiki_0.1.4_linux_amd64.tar.gz"
      sha256 "5f7615c939eef910daa6f59e6d2d2e8517cd899ce90cda9d05115cdacfd47f33"
      define_method(:install) do
        bin.install "awiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/awiki/releases/download/v0.1.4/awiki_0.1.4_linux_arm64.tar.gz"
      sha256 "bbdfc7d933d17e06fac4800e6c84612218830d6d3140d347d1e4cd1d75e3276b"
      define_method(:install) do
        bin.install "awiki"
      end
    end
  end

  test do
    system bin/"awiki", "version"
  end
end
