# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrakenCli < Formula
  desc "Browserless Craken product CLI"
  homepage "https://github.com/corca-ai/craken-cli"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.6/craken_0.1.6_darwin_amd64.tar.gz"
      sha256 "e2efeb29a369422fd858712a4f04d27c6a915f8c965de3c4107be0a20bfa3432"

      define_method(:install) do
        bin.install "craken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.6/craken_0.1.6_darwin_arm64.tar.gz"
      sha256 "924d21af3237ab3711098ee5a765f7aabbeb05a5407e64334c1c7196d01d9e85"

      define_method(:install) do
        bin.install "craken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.6/craken_0.1.6_linux_amd64.tar.gz"
      sha256 "538d286e6b68baa132cf33d73436a1502cd201b1ec23c88b706f0f677d8a00a0"
      define_method(:install) do
        bin.install "craken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/craken-cli/releases/download/v0.1.6/craken_0.1.6_linux_arm64.tar.gz"
      sha256 "75e622188a4ff4afdd9a439c246b25a4e6dfe6c459e7a12652c9a33ea7434abc"
      define_method(:install) do
        bin.install "craken"
      end
    end
  end

  test do
    system bin/"craken", "version"
  end
end
