# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SahCli < Formula
  desc "SCIENCE@home worker CLI for background agent contributions"
  homepage "https://github.com/corca-ai/sah-cli"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corca-ai/sah-cli/releases/download/v0.11.0/sah_0.11.0_darwin_amd64.tar.gz"
      sha256 "9c1832e27f31194fe4ea7d653e3b5a3cb032366f2dee99c70f326b9b0c7d3c7b"

      define_method(:install) do
        bin.install "sah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corca-ai/sah-cli/releases/download/v0.11.0/sah_0.11.0_darwin_arm64.tar.gz"
      sha256 "25ab84ee05f19496981d4b0442ae48be7fd42e494636b87a0b6ea4242e072b34"

      define_method(:install) do
        bin.install "sah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/sah-cli/releases/download/v0.11.0/sah_0.11.0_linux_amd64.tar.gz"
      sha256 "dbd6574cccbf98d4f72bb316196f13d014f39963c85daa2d992d08845838cc2d"
      define_method(:install) do
        bin.install "sah"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corca-ai/sah-cli/releases/download/v0.11.0/sah_0.11.0_linux_arm64.tar.gz"
      sha256 "d7b671c15d02032eac9a07d78dbe156da8ecd621f726d07a1a12a471c4380738"
      define_method(:install) do
        bin.install "sah"
      end
    end
  end

  test do
    system bin/"sah", "version"
  end
end
